// <auto-generated />
using IOT_Project_MyDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IOT_Project_MyDB.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220302020059_v1.4")]
    partial class v14
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IOT_Priject_Domin.Model.Daily", b =>
                {
                    b.Property<int>("DaiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DaiApplication")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DaiHandling")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Daiagent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Daiapplicant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Daidate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Daidepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dainote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Daiuse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("DaiId");

                    b.ToTable("Daily");
                });

            modelBuilder.Entity("IOT_Priject_Domin.Model.Dailydetailed", b =>
                {
                    b.Property<int>("Dailys")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Daisname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Daisnote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Daisnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Daisprice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Daisserial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Daisspecifications")
                        .HasColumnType("int");

                    b.Property<int>("Daisunit")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Dailys");

                    b.ToTable("Dailydetailed");
                });

            modelBuilder.Entity("IOT_Priject_Domin.Model.Meeting", b =>
                {
                    b.Property<int>("MyPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MyPName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MyPaccommodate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MyPadministrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MyPconditioner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MyPdispenser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MyPfloor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MyPnetwork")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MyPnote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MyPphotograph")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MyPprojector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MyPrange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MyPseat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MyPwhiteboard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("MyPId");

                    b.ToTable("Meeting");
                });

            modelBuilder.Entity("IOT_Priject_Domin.Model.ReceItemDetails", b =>
                {
                    b.Property<int>("RecesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RecesName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Recesinventory")
                        .HasColumnType("int");

                    b.Property<string>("Recesnote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recespecifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Recesremaining")
                        .HasColumnType("int");

                    b.Property<int>("Recesuse")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("RecesId");

                    b.ToTable("ReceItemDetails");
                });

            modelBuilder.Entity("IOT_Priject_Domin.Model.ReceItineraryDetails", b =>
                {
                    b.Property<int>("RececId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RececAccompanied")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receccar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rececdepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rececend")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rececexhibition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recechotel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rececmeal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rececmeeting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rececnote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rececstart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recectrip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("RececId");

                    b.ToTable("ReceItineraryDetails");
                });

            modelBuilder.Entity("IOT_Priject_Domin.Model.Receptionbase", b =>
                {
                    b.Property<int>("ReceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ReceFlight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceVisiting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receapplicant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recedepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receitems")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recemain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receneed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recenote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recenumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recerequirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recestay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recethe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recetime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receunawares")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recevisitors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("ReceId");

                    b.ToTable("Receptionbase");
                });
#pragma warning restore 612, 618
        }
    }
}
