// <auto-generated />
using IOT_Project_MyDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IOT_Project_MyDB.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IOT_Priject_Domin.Model.staff_entering", b =>
            modelBuilder.Entity("IOT_Priject_Domin.Model.Leave", b =>
                {
                    b.Property<int>("sid")
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Taskid")
                    b.Property<int>("ApplyDemo")
                        .HasColumnType("int");

                    b.Property<DateTime>("birthday")
                    b.Property<DateTime>("ApplyTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("contract_deadline")
                        .HasColumnType("int");

                    b.Property<string>("culturedegree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("departmentid")
                        .HasColumnType("int");

                    b.Property<int>("explain")
                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<string>("health")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("qualifying_period")
                    b.Property<string>("LeaveCause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("roleid")
                        .HasColumnType("int");

                    b.Property<int>("roletype")
                        .HasColumnType("int");

                    b.Property<int>("sex")
                        .HasColumnType("int");

                    b.Property<string>("site")
                    b.Property<string>("LeaveImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("speciality")
                    b.Property<string>("LeaveRemark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("treatment")
                    b.Property<string>("LeaveType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                    b.Property<string>("Proposer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("vouchtime")
                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("whether")
                        .HasColumnType("int");

                    b.HasKey("sid");

                    b.ToTable("taff_entering");
                });

            modelBuilder.Entity("IOT_Priject_Domin.Model.userkinsfolk", b =>
                {
                    b.Property<int>("uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Taskid")
                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("kinsfolk_post")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kinsfolkname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("relation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("uid");
                    b.HasKey("Id");

                    b.ToTable("userkinsfolk");
                    b.ToTable("Leave");
                });
#pragma warning restore 612, 618
        }
    }
}
