// <auto-generated />
using IOT_Project_MyDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IOT_Project_MyDB.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

<<<<<<< HEAD
            modelBuilder.Entity("IOT_Priject_Domin.Model.Carapply", b =>
                {
                    b.Property<int>("CarapplyId")
=======
            modelBuilder.Entity("IOT_Priject_Domin.Model.ResourcesRequirements", b =>
                {
                    b.Property<int>("Id")
>>>>>>> d20fe4c775673a04dc654d0243dddcf60287df85
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

<<<<<<< HEAD
                    b.Property<string>("CarapplyApproach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarapplyCommon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarapplyDepart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarapplyDeparture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarapplyDriver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarapplyEndDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarapplyFinish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarapplyKilometre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarapplyPlate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarapplyPractical")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarapplyProposer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarapplyProposerDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarapplyReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarapplyRemark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarapplyRiding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarapplyStartDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarapplyTProposerDemp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarapplyTarget")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CarapplyTaskId")
                        .HasColumnType("int");

                    b.Property<string>("CarapplyWeek")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarapplyId");

                    b.ToTable("Carapply");
                });

            modelBuilder.Entity("IOT_Priject_Domin.Model.HandOver", b =>
                {
                    b.Property<int>("HId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HandDemp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandDempCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandDempContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandFinceCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandFinceContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandHeir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandImgurl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandProve")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandRemark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandStativeCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandStativeContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Handdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Handpostion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("HId");

                    b.ToTable("HandOver");
                });

            modelBuilder.Entity("IOT_Priject_Domin.Model.Interview", b =>
                {
                    b.Property<int>("TnterviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InterviewAward")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterviewCase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterviewChnnel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterviewCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterviewDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterviewEmploy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterviewEndDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterviewLabor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterviewLeaving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterviewLister")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterviewListerDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterviewListerDemp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterviewManage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterviewPay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterviewProspect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterviewRecord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterviewRemark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterviewSatisfaction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterviewStaffName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterviewStaffNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterviewStaion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterviewStarDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterviewTrain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("TnterviewId");

                    b.ToTable("Interview");
=======
                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Annex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Applicationdepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Applicationtime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Education")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jobdescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jobrequirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jobtitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numberofpeopleonhand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numberofrecruits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Other")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Probationperiod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Professionalrequirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reasonforapplication")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salarypackage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ResourcesRequirements");
>>>>>>> d20fe4c775673a04dc654d0243dddcf60287df85
                });
#pragma warning restore 612, 618
        }
    }
}
